---
- name: Windows | Check if Program Files (x86) exists
  win_stat:
    path: C:\Program Files (x86)
  register: check_path

- name: Windows | Set Win Path (x86)
  set_fact:
    wazuh_agent_win_path: "{{ wazuh_winagent_config.install_dir_x86 }}"
    wazuh_agent_win_auth_path: "{{ wazuh_winagent_config.auth_path_x86 }}"
  when:
    - check_path.stat.exists

- name: Windows | Set Win Path (x64)
  set_fact:
    wazuh_agent_win_path: "{{ wazuh_winagent_config.install_dir }}"
    wazuh_agent_win_auth_path: "{{ wazuh_winagent_config.auth_path_x86 }}"
  when:
    - not check_path.stat.exists

- name: Windows | Check if Wazuh installer is already downloaded
  win_stat:
    path: "{{ wazuh_winagent_config.download_dir }}wazuh-agent-{{ wazuh_winagent_config.version }}-{{ wazuh_winagent_config.revision }}.msi"
  register: wazuh_package_downloaded

- name: Windows | Download Wazuh Agent package
  win_get_url:
    url: "{{ wazuh_winagent_config.repo }}wazuh-agent-{{ wazuh_winagent_config.version }}-{{ wazuh_winagent_config.revision }}.msi"
    dest: "{{ wazuh_winagent_config.download_dir }}"
  when:
    - not wazuh_package_downloaded.stat.exists

- name: Windows | Verify the Wazuh Agent installer
  win_stat:
    path: "{{ wazuh_winagent_config.download_dir }}wazuh-agent-{{ wazuh_winagent_config.version }}-{{ wazuh_winagent_config.revision }}.msi"
    get_checksum: true
    checksum_algorithm: md5
  register: wazuh_agent_status
  failed_when:
    - wazuh_agent_status.stat.checksum != wazuh_winagent_config.md5

- name: Windows | Install Agent if not already installed
  win_package:
    path: "{{ wazuh_winagent_config.download_dir }}wazuh-agent-{{ wazuh_winagent_config.version }}-{{ wazuh_winagent_config.revision }}.msi"
    state: present

- name: Windows | Check if client.keys exists
  win_stat: path="{{ wazuh_agent_win_path }}client.keys"
  register: check_windows_key
  tags:
    - config

- name: Retrieving authd Credentials
  include_vars: authd_pass.yml
  tags:
    - config

- name: Windows | Register agent
  win_shell: >
    {{ wazuh_agent_win_auth_path }}
    -m {{ wazuh_managers.0.address }}
    -p {{ wazuh_agent_authd.port }}
    {% if authd_pass is defined %} -P {{ authd_pass }}{% endif %}
  register: agent_auth_output
  notify: Windows | Restart Wazuh Agent
  when:
    - wazuh_agent_authd.enable
    - not check_windows_key.stat.exists or check_windows_key.stat.size == 0
    - wazuh_managers.0.address is not none
  tags:
    - config

- name: Windows | Check if ossec folder is accessible
  win_file:
    path: "{{ wazuh_agent_win_path }}"
    state: directory

- name: Windows | Installing agent configuration (ossec.conf)
  template:
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: "{{ wazuh_agent_win_path }}ossec.conf"
  notify: Windows | Restart Wazuh Agent
  tags:
    - config

- name: Windows | Installing local_internal_options.conf
  win_template:
    src: var-ossec-etc-local-internal-options.conf.j2
    dest: "{{ wazuh_agent_win_path }}local_internal_options.conf"
  notify: Windows | Restart Wazuh Agent
  tags:
    - config

- name: Windows | Delete downloaded Wazuh agent installer file
  win_file:
    path: "{{ wazuh_winagent_config.download_dir }}wazuh-agent-{{ wazuh_winagent_config.version }}-{{ wazuh_winagent_config.revision }}.msi"
    state: absent
